### ISSUE TITLE
Give choice to choose aur package manager

### ISSUE THREAD

**Issue by qlrd** [xrhstosmour/arch-tuner#1]
This is a awesome project, congratulations!

I saw that you added paru as AUR package manager; i understand that this repo it's your dotfiles, but these configurations are incredible for restoring backups.

So, i think it will be nice if a option to choose the AUR package manager (paru, yay, etc.) can be added. I can work on PR if you want.

What do you think?

**Comment by xrhstosmour** [comment]
Thank you for your kind words and feedback!

Yes, this project is still evolving, and I'm constantly working to refine and improve it. Your suggestion about providing an option to choose the preferred AUR package manager is excellent. While I've added paru, it would be beneficial to allow the flexibility between paru, yay, and others.

I'd be truly grateful if you're open to contributing and submitting a PR for this feature. 

Let me know if you require any additional information from me to proceed.

**Comment by qlrd** [comment]
Before I proceed, maybe it's interestting to propose the creation of a `build.sh` script, 
that is, a one line command (with arguments) that can configure, clone and execute properly the [`scripts/install.sh`](https://github.com/xrhstosmour/dotfiles/blob/main/scripts/install.sh), like the [raspiblitz's `build_sdcard.sh`](https://github.com/raspiblitz/raspiblitz/blob/v1.9/build_sdcard.sh)

For example:

```
$> wget https://raw.githubusercontent.com/xrhstosmour/dotfiles/main/build.sh | sudo bash build.sh
```

configure, clone and execute [`scripts/install.sh`](https://github.com/xrhstosmour/dotfiles/blob/main/scripts/install.sh) with default arguments (paru as default)

Or:

```
$> wget https://raw.githubusercontent.com/xrhstosmour/dotfiles/main/build.sh | sudo bash build.sh --aur yay
```

configure, clone and execute [`scripts/install.sh`](https://github.com/xrhstosmour/dotfiles/blob/main/scripts/install.sh) with yay as aur package manager:

Or:

```
$> wget https://raw.githubusercontent.com/xrhstosmour/dotfiles/main/build.sh | sudo bash build.sh --aur aurutils --packages-desktop <my-custom-desktop-apps.txt>
```

configure, clone and execute [`scripts/install.sh`](https://github.com/xrhstosmour/dotfiles/blob/main/scripts/install.sh) with aurutils as aur package manager and custom [desktop packages](https://github.com/xrhstosmour/dotfiles/blob/main/scripts/packages/desktop.txt)

What do you think?

**Comment by qlrd** [comment]
Created a first (but not tested yet) experiment [here](https://github.com/qlrd/archlinux-dotfiles/blob/main/build.sh)

**Comment by xrhstosmour** [comment]
I have first to finalize the installation procedure and eliminate the remaining bugs, before proceeding with the above.
I will need some time for that.

**Comment by xrhstosmour** [comment]
The yay AUR helper feature has been added. 
Regarding the build.sh script you mentioned, consider opening a pull request on a different issue specifically related to it. 
If you need any configurations related to yay or the option for any other AUR helper, please inform me or open a new issue/pull request. 
I am closing this issue for the time being.
